# Generated by Django 4.2.7 on 2024-01-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Slocation', models.CharField(max_length=100)),
                ('Sprincipal', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Reentermail', models.EmailField(max_length=254)),
            ],
        ),
    ]
